# SonarQube Configuration
sonar.projectKey=com.promix.platform:rule-engine
sonar.projectName=rule-engine
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.java.source=21
sonar.java.target=21
sonar.sourceEncoding=UTF-8
# SonarQube Server Configuration
sonar.host.url=https://sonar.promixhub.com
sonar.token=squ_8de7e7bfdabc53cfbcf51553595f5c281c840c35
