package vn.viettel.vds.promotion.rule.engine.domain.service.operator.impl;

import org.springframework.stereotype.Component;
import vn.viettel.vds.promotion.rule.engine.domain.service.operator.OperatorTranslator;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Generic translator for operator {@code metadata.access}.
 *
 * <p>Reads {@code schema_type}, {@code field_key}, {@code data_type}, {@code comparator}, and
 * {@code value} from the rule-node params map (set by the FE rule builder from the virtual
 * {@code OperatorOption} generated by T15). Renders the full Drools fact-pattern line.
 *
 * <p><b>Schema type → fact variable mapping (Pha 1):</b>
 * <ul>
 *   <li>{@code customer} / {@code customer_metadata} → {@code $customer: Customer(...)}</li>
 *   <li>{@code order} / {@code order_metadata}       → {@code $order: Order(...)}</li>
 * </ul>
 *
 * <p><b>Map accessor by schema type:</b>
 * <ul>
 *   <li>customer → {@code attrs["fieldKey"]} (Customer.attrs field)</li>
 *   <li>order    → {@code metadata["fieldKey"]} (Order.metadata field)</li>
 * </ul>
 *
 * <p><b>Data-type → comparator → DRL rendering:</b>
 * <ul>
 *   <li>STRING  + equals/not_equals/in/not_in/contains/starts_with</li>
 *   <li>NUMBER  + equals/gte/lte/between (value can be a Number or String)</li>
 *   <li>BOOLEAN + is_true/is_false</li>
 *   <li>DATE    + before/after/equals/between (ISO-8601 string value)</li>
 *   <li>LIST    + contains/not_contains/size_gte/size_lte</li>
 * </ul>
 *
 * <p>Null-safety: {@code attrs} / {@code metadata} map is checked for non-null before key access.
 */
@Component
public class MetadataAccessOperatorTranslator implements OperatorTranslator {

    private static final String OPERATOR_NAME = "metadata.access";

    @Override
    public String getOperatorName() {
        return OPERATOR_NAME;
    }

    @Override
    public Integer getVersion() {
        return 1;
    }

    @Override
    public boolean supports(String operatorName, Integer version) {
        return OPERATOR_NAME.equals(operatorName) &&
                (version == null || version.equals(getVersion()));
    }

    @Override
    public String translate(String nodeId, Map<String, Object> params, String reasonCode) {
        String schemaType = required(params, "schema_type");
        String fieldKey   = required(params, "field_key");
        String dataType   = required(params, "data_type");
        String comparator = required(params, "comparator");
        Object value      = params.get("value");

        String mapField   = mapFieldName(schemaType);   // "attrs" or "metadata"
        String accessor   = mapField + "[\"" + escape(fieldKey) + "\"]";  // attrs["vip_tier"]
        String constraint = renderConstraint(dataType, accessor, mapField, comparator, value);

        String factVar    = factVariable(schemaType);   // "$customer: Customer" or "$order: Order"
        return "        " + factVar + "(" + mapField + " != null && " + constraint + ")\n";
    }

    // --- routing ---

    private String renderConstraint(String dataType, String accessor, String mapField,
                                    String comparator, Object value) {
        return switch (dataType.toUpperCase()) {
            case "STRING"  -> renderString(accessor, comparator, value);
            case "NUMBER"  -> renderNumber(accessor, comparator, value);
            case "BOOLEAN" -> renderBoolean(accessor, comparator);
            case "DATE"    -> renderDate(accessor, comparator, value);
            case "LIST"    -> renderList(accessor, comparator, value);
            default -> throw new IllegalArgumentException(
                    "Unsupported data_type '" + dataType + "' for operator " + OPERATOR_NAME);
        };
    }

    // --- STRING ---

    private String renderString(String accessor, String comparator, Object value) {
        return switch (comparator) {
            case "equals"      -> accessor + " == \"" + escape(value) + "\"";
            case "not_equals"  -> accessor + " != \"" + escape(value) + "\"";
            case "in"          -> accessor + " in (" + toQuotedList(asList(value)) + ")";
            case "not_in"      -> accessor + " not in (" + toQuotedList(asList(value)) + ")";
            case "contains"    -> "((String) " + accessor + ").contains(\"" + escape(value) + "\")";
            case "starts_with" -> "((String) " + accessor + ").startsWith(\"" + escape(value) + "\")";
            default -> throw new IllegalArgumentException(
                    "STRING does not support comparator '" + comparator + "' for " + OPERATOR_NAME);
        };
    }

    // --- NUMBER ---

    private String renderNumber(String accessor, String comparator, Object value) {
        String num = "((Number) " + accessor + ").doubleValue()";
        return switch (comparator) {
            case "equals" -> num + " == " + value;
            case "gte"    -> num + " >= " + value;
            case "lte"    -> num + " <= " + value;
            case "between" -> {
                @SuppressWarnings("unchecked")
                Map<String, Object> range = (Map<String, Object>) value;
                yield num + " >= " + range.get("min") + " && " + num + " <= " + range.get("max");
            }
            default -> throw new IllegalArgumentException(
                    "NUMBER does not support comparator '" + comparator + "' for " + OPERATOR_NAME);
        };
    }

    // --- BOOLEAN ---

    private String renderBoolean(String accessor, String comparator) {
        return switch (comparator) {
            case "is_true"  -> "Boolean.TRUE.equals(" + accessor + ")";
            case "is_false" -> "Boolean.FALSE.equals(" + accessor + ")";
            default -> throw new IllegalArgumentException(
                    "BOOLEAN does not support comparator '" + comparator + "' for " + OPERATOR_NAME);
        };
    }

    // --- DATE ---

    private String renderDate(String accessor, String comparator, Object value) {
        String inst = "((java.time.Instant) " + accessor + ")";
        return switch (comparator) {
            case "equals" -> inst + ".equals(java.time.Instant.parse(\"" + value + "\"))";
            case "after"  -> inst + ".isAfter(java.time.Instant.parse(\"" + value + "\"))";
            case "before" -> inst + ".isBefore(java.time.Instant.parse(\"" + value + "\"))";
            case "between" -> {
                @SuppressWarnings("unchecked")
                Map<String, String> range = (Map<String, String>) value;
                yield inst + ".isAfter(java.time.Instant.parse(\"" + range.get("from") + "\")) && "
                        + inst + ".isBefore(java.time.Instant.parse(\"" + range.get("to") + "\"))";
            }
            default -> throw new IllegalArgumentException(
                    "DATE does not support comparator '" + comparator + "' for " + OPERATOR_NAME);
        };
    }

    // --- LIST ---

    private String renderList(String accessor, String comparator, Object value) {
        String list = "((java.util.List) " + accessor + ")";
        return switch (comparator) {
            case "contains"     -> list + ".contains(\"" + escape(value) + "\")";
            case "not_contains" -> "!" + list + ".contains(\"" + escape(value) + "\")";
            case "size_gte"     -> list + ".size() >= " + value;
            case "size_lte"     -> list + ".size() <= " + value;
            default -> throw new IllegalArgumentException(
                    "LIST does not support comparator '" + comparator + "' for " + OPERATOR_NAME);
        };
    }

    // --- schema type helpers ---

    /**
     * Maps schema_type to the Drools map field name on the Fact POJO.
     * customer / customer_metadata → {@code attrs}  (Customer.attrs)
     * order    / order_metadata    → {@code metadata} (Order.metadata)
     */
    private String mapFieldName(String schemaType) {
        return switch (schemaType.toLowerCase()) {
            case "customer", "customer_metadata" -> "attrs";
            case "order", "order_metadata"       -> "metadata";
            default -> throw new IllegalArgumentException(
                    "Unsupported schema_type '" + schemaType + "' for Pha 1 of " + OPERATOR_NAME
                            + ". Supported: customer, customer_metadata, order, order_metadata");
        };
    }

    /**
     * Maps schema_type to a Drools fact pattern prefix (variable + class).
     */
    private String factVariable(String schemaType) {
        return switch (schemaType.toLowerCase()) {
            case "customer", "customer_metadata" -> "$customer: Customer";
            case "order", "order_metadata"       -> "$order: Order";
            default -> throw new IllegalArgumentException(
                    "Unsupported schema_type '" + schemaType + "' for Pha 1 of " + OPERATOR_NAME);
        };
    }

    // --- util ---

    private String required(Map<String, Object> params, String key) {
        Object v = params.get(key);
        if (v == null) {
            throw new IllegalArgumentException(
                    "Missing required param '" + key + "' for operator " + OPERATOR_NAME);
        }
        return v.toString();
    }

    @SuppressWarnings("unchecked")
    private List<Object> asList(Object value) {
        if (value instanceof List) {
            return (List<Object>) value;
        }
        if (value instanceof String s) {
            return List.of(s);
        }
        throw new IllegalArgumentException(
                "Expected List or String for in/not_in comparator in " + OPERATOR_NAME);
    }

    private String toQuotedList(List<Object> values) {
        return values.stream()
                .map(v -> "\"" + escape(v) + "\"")
                .collect(Collectors.joining(", "));
    }

    private String escape(Object v) {
        if (v == null) return "";
        return v.toString().replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
